spring:
    application:
        name: hhh-consumer-admin

server:
    port: 9001 #启动端口;

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  httpclient:
    enabled: false