spring:
  application:
    name: hhh-center

server:
  port: 8761 #启动端口

#eureka:
#  client:
#    #由于该应用为注册中心,设置为false,表明不向注册中心注册自己
#    register-with-eureka: false
#    fetch-registry: false #为true时，可以启动，但报异常：Cannot execute request on any known server
#    serviceUrl:
#      defaultZone: http://localhost:${server.port}/eureka/
#  server:
#    enable-self-preservation: false     #禁用自我保护机制
