spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: add_request_parameter_route
        uri: lb://hhh-provider-member
        filters:
        - AddRequestParameter=foo, bar
        predicates:
        - Method=GET
